### ISSUE TITLE
expr: syntax error: unexpected argument '9465871'

### ISSUE THREAD

**Issue by jiapei100** [cth103/asdcplib-cth#3]
Hi, Carl:
Any updates for your **dcp** recently?

I'm trying to build it under Ubuntu 22.04 now. My **ENV** is:

```console
➜  ~ uname -r
5.15.0-27-generic
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
➜  ~ gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  ~ python --version
Python 3.10.4
```

And, while I tried to `./configure` your [asdcplib-cth](https://github.com/cth103/asdcplib-cth), I got the following **ERROR** messages:
Can you please **"FIX** it?

```console
...
checking if OpenSSL version is >= 0.9.7... ./configure: line 15689: /* Synthesize OPENSS_VERSION_NUMBER with the layout 0xMNN00PPS */
# define OPENSS_VERSION_NUMBER          \: syntax error: operand expected (error token is "/* Synthesize OPENSS_VERSION_NUMBER with the layout 0xMNN00PPS */
# define OPENSS_VERSION_NUMBER          \")
expr: syntax error: unexpected argument '9465871'
no
configure: WARNING: Found # define OPENSSL_VERSION_TEXT OpenSSL 3.0.2 15 Mar 2022, which is older than required. Possible compilation failure.
checking for Expat XML Parser... no
checking for Xerces C++ Parser... no
checking for --with-python... no
...
```

Cheers
Pei

**Comment by cth103** [comment]
Hi, can you try with the `carl` branch of this repo: https://github.com/cth103/asdcplib/

**Comment by jiapei100** [comment]
I got the following **ERROR** messages:

```console
➜  asdcplib git:(carl) ./waf configure
fatal: No tags can describe 'ee04871698c10aa4d9736d3457bf74ff68a07b5d'.
Try --always, or create some tags.
Setting top to                           : ....../asdcplib 
Setting out to                           : ....../asdcplib/build 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'openssl'                   : yes 
Checking for boost library >= 1.45       : yes 
Checking for boost filesystem library    : yes 
Checking for header valgrind/memcheck.h  : yes 
Traceback (most recent call last):
  File "....../asdcplib/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "....../asdcplib/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Scripting.py", line 179, in run_commands
    ctx=run_command(cmd_name)
  File "....../asdcplib/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Scripting.py", line 170, in run_command
    ctx.execute()
  File "....../asdcplib/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "....../asdcplib/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "....../asdcplib/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "....../asdcplib/wscript", line 84, in configure
    conf.recurse('src')
  File "....../asdcplib/.waf3-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "....../asdcplib/src/wscript", line 7, in configure
    major_minor = '%s.%s.0' % (s[0], s[1])
IndexError: list index out of range
```

Cheers

**Comment by cth103** [comment]
I just pushed a missing tag... could you try a `git fetch --tags` and then try again?

**Comment by jiapei100** [comment]
@cth103 
Great... it's built, successfully... What is **waf**? It's in binary...
And it seems **cmake** is good enough...

**Comment by cth103** [comment]
https://waf.io/
It's written in Python but packed into a binary to make distribution easier.  It's always worked great for me!

**Comment by jiapei100** [comment]
@cth103 
That's pretty convenient.... ^_^ Thank you for your detailed explaination...
I met the same issue [https://github.com/cth103/libdcp/issues/6](https://github.com/cth103/libdcp/issues/6), can you please take a look? It's already **OpenJPEG 2.5.0** now...
